name: EAS Update (manual)

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          eas-version: latest
          expo-cache: false
          eas-cache: false

      - run: npm ci
      - run: eas update --auto --non-interactive
